Removing terraform plan

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -32,11 +32,11 @@ jobs:
         id: validate
         run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
       
       - name: Terraform Show
         if: github.event_name == 'pull_request'
@@ -51,10 +51,12 @@ jobs:
         run: bash installScript.sh
 
       - name: Cloudfix-Linter Init
+        id: linterinit
         if: github.event_name == 'pull_request'
         run: export CLOUDFIX_FILE=true ; ./cloudfix-linter/cloudfix-linter init
 
       - name: Cloudfix-Linter Recco
+        id: linterrecco
         if: github.event_name == 'pull_request'
         run: export CLOUDFIX_FILE=true ; ./cloudfix-linter/cloudfix-linter recco --json
 
@@ -68,7 +70,8 @@ jobs:
             const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+            #### Cloudfix-Linter Init 🤖\`${{ steps.linterinit.outcome }}\`
+            #### Cloudfix-Linter Reccomendations 🤖\`${{ steps.linterrecco.outcome }}\`
 
             <details><summary>Show Plan</summary>
 
@@ -87,9 +90,9 @@ jobs:
               body: output
             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
